abstract class HowTheyKnowEachOther {
  static List<String> getHowTheyKnowEachOther() {
    var hows = [
      'went to high school together',
      'co-workers at a nuclear power plant',
      'attend the same school for exotic dancers',
      'in the same jail',
      'beekeepers together',
      'they sell shoes together',
      'in a support group for people who are afraid of snakes',
      'divorcees',
      'in the same Uber',
      'dentist and patient',
      'drug dealer and client',
      'co-workers at the video store',
      'they\'re exes',
      'volunteers at a homeless shelter',
      'standing in line for a concert together',
      'online gaming friends',
      'online sleuths',
      'on a ghost hunting team',
      'they carpool together',
      'in the same yoga class',
      'twins',
      'in a juggling class together',
      'taking home improvement 101 together',
      'podcast hosts',
      'support group members',
      'coach and athlete',
      'rivals',
      'pen pals',
      'band mates',
      'travel buddies',
      'in-laws',
      'interns at Google',
      'they make maps together',
      'co-workers at Forever 21',
      'neighbors',
      'cousins',
      'business partners',
      'fitness buddies',
      'personal trainer and trainee',
      'in a book club together',
      'boss and employee at the factory',
      'on a bowling team together',
      'lobsters in the lobster tank at Red Lobster',
      'siblings',
      'NASA employees',
      'stuck inside the same whale together',
      'amateur detectives',
      'ren faire performers',
      'roller derby teammates',
      'dog park regulars',
      'regulars at the local pub',
      'escape room enthusiasts'
    ];
    return hows;
  }
}
