abstract class Objects {
  static List<String> getObjects() {
    var objects = [
      'door knob',
      'elephant',
      'scissors',
      'mirror',
      'oven mitt',
      'cake batter',
      'pile of stuff',
      'toxic waste',
      'chocolate chip cookie',
      'apple core',
      'aardvark',
      'atom',
      "Beyonce's hot sauce",
      'balloon',
      'ball of steel',
      'brick',
      'chimney',
      'comb',
      'cone',
      "Dracula's fang",
      'dented hood',
      'deer hoof',
      'elephant tusk',
      "Elon Musk's wallet",
      'ear lobe',
      'football',
      'fancy hat',
      'four foot sub',
      'gas pipe',
      'green thumb',
      'golf ball',
      'hunting knife',
      'helmet',
      'hacksaw',
      'hill',
      'igloo',
      'ice cube',
      'important document',
      'jar of marmalade',
      'Jurassic Park DVD',
      'stick of beef jerky',
      'kickball',
      'kite',
      'kinky wire',
      'laser pointer',
      'stick of lipstick',
      "pair of Levi's",
      'marker',
      'map of Disney World',
      'most of an Ikea desk',
      'nonstick pan',
      'novel',
      'nuclear seahorse',
      'octopus tentacle',
      'oleander flower',
      'outie bellybutton',
      'pumpkin',
      'previously used gloves',
      'plastic boat',
      "Grandma's quilt",
      'quarter',
      'quart of milk',
      'radioactive waste',
      'rhinoceros horn',
      'real Gucci bag',
      'saucer',
      'Scottish kilt',
      'shaded lawn chair',
      'trailer',
      'bottle of tonic water',
      'wisdom tooth',
      'umbrella',
      'someone else\'s underwear',
      'underwhelming dessert',
      'sandwich from Victory',
      'vanilla bean',
      'volume knob',
      'water hose',
      'whoopie cushion',
      'waffle maker',
      'bottle of Windex',
      'X-Men comic book',
      'x-ray machine',
      'a broken xylophone',
      'yesterdays mail',
      'yellow ribbon',
      'yikes machine',
      'zoo chart',
      'zoology text book',
      'zipper'
    ];
    return objects;
  }
}
