abstract class Place {
  static List<String> getPlaces() {
    var places = ['Miami',
      'Subway restaurant',
      'North Pole',
      'inside an active volcano',
      'a tiny closet',
      'a dressing room',
      'California pizza kitchen',
      'an airport',
      'a submarine',
      'Atlanta Aquarium',
      'the Cheers bar',
      'a bounce house',
      'a banana stand',
      'on a ship',
      'green house',
      'a donut shop',
      'a walk-in closet',
      'a Starbucks',
      'a waiting room',
      'the Cocoa Puffs factory',
      'in a canoe floating down the Mississippi River'
      'a tree house',
      'a man cave',
      'a pumpkin patch',
      'a cactus farm',
      'Elon Musk\'s brain',
      'dentist office',
      'the Statue of Liberty',
      'in line to see Santa Claus',
      'a golf course',
      'the break room',
      'on the set of the latest superhero sequel',
      'a surveillance tower',
      'a cop car',
      'Target',
      'a French chateau',
      'a book store',
      'a movie theater',
      'in a bank vault',
      'outside the boss\'s house',
      'in the middle of a hold up',
      'a jewelry store',
      'gym class',
      'the arcade',
      'Forever 21',
      'Mars',
      'Facebook headquarters',
      'the smoking lounge',
      'high school prom',
      'the glass factory',
      'in the trenches of a war',
      'the circus'
    ];
    return places;
  }
}