abstract class Problem {
  static List<String> getProblems() {
    var problems = [
      'trapped in a cave',
      'lost wedding ring',
      'lost their weed',
      'accidentally quit their job',
      'lost in a zoo',
      'assembling an Ikea desk',
      'figuring out what to have for dinner',
      'choosing the best pumpkin',
      'curing a spider bite',
      'too many leaves',
      'in dire need of Chick-fil-A',
      'you have 10,000 spoons but all you need is a knife',
      'not enough slotted spoons',
      'everything is real sticky',
      'the world is about to end',
      'earth is about to get struck by a giant chocolate ball',
      'all the jolly ranchers have disappeared',
      'dogs have turned into cats and cats have turned into dogs',
      'hunting for treasure with an ambiguous map',
      'the Easter Bunny won\'t wake up',
      'the pyramids turned to clay',
      'can\'t tell if this fish sandwich is still good or not',
      'clothes are too big',
      'late for the big presentation',
      'all the bunnies are trying to be like Bad Bunny',
      'choosing a new paint color for a room',
      'at Home Depot but not sure why',
      'drank real coffee instead of decaf',
      'the Kool-Aid man is running for President',
      'there\'s no more podcasts',
      'all the bank tellers are mice now',
      'trying to play Monopoly without instructions',
      'all the water has turned into Yoo-hoo',
      'changing a baby\'s diaper',
      'flat tire',
      'someone stole your blanket',
      'its way too purple',
      'traffic is completely stopped',
      'out of essential oils',
      'all the cell phone chargers have disappeared',
      'hunting for Bugs Bunny',
      'the bees want their honey back and you\'re allergic to bees',
      'stuck in the big cat house at the zoo',
      'a bear is sleeping on top of you',
      'at the arcade with jelly instead of quarters',
      'you really, really want to turn into a vampire',
      'you really, really want to turn into a zombie',
      'can\'t sleep',
      'ate the wrong kind of mushrooms',
      'Uber driver is falling asleep',
      'there is a small hole in the bottom of your canoe'
    ];
    return problems;
  }
}