abstract class UnusualEvent {
  static List<String> getUnusualEvents() {
    var unusualEvents = [
      'meatball convention',
      'spontaneous combustion research fair',
      'horse braiding competition',
      'parrot groomers association annual meeting',
      'pumpkin pageant',
      'Mr. Rogers on Broadway',
      'local chapter of Vampires Anonymous is opening',
      'Chik-Fil-A grand opening',
      'vacuum convention',
      'roller skating enthusiasts convention',
      'microwave innovations competition',
      'burning of the clocks festival',
      'the battle of the oranges',
      'roadkill festival',
      'barrel assembly workshop',
      'world bog snorkeling championships',
      'spouse carrying world championships',
      'hot dog eating contest',
      'baby jumping festival',
      'melon festival',
      'trumpet festival',
      'pizza fest',
      'heavy metal knitting competition',
      'worm charming festival',
      'international air guitar championships',
      'frog festival',
      'balloon innovation festival',
      'everyone in town thinks they\'re a windmill',
      'an asteroid is going to hit earth soon',
      'furry convention',
      'book burning convention',
      'a gang of talking pit bulls just came to town',
      'the ghost of George Washington is coming',
      'Burning Man',
      'octopus festival',
      'pigsty celebration',
      'an alien invasion but they\'re actually just cowboys',
      'all the cell phones just turned into bananas',
      'all the cats in town have thumbs for one day only',
      'mouse opera',
      'car wash fundraiser for ant safety awareness',
      'the floor is lava',
      'the empire state building is going to be dressed up like Santa Claus',
      'a beer fest, but with hot chocolate instead',
      'a high school is having an election for their class cookie aficionado',
      'the animatronic animals at a Chuck E. Cheese are voting for a union',
      'sweater knitting contest',
      'Beavis and Butthead memoir book signing',
      'tattoo laser removal convention',
      'clergy-aholics anonymous meeting',
      'zombie and vampire wrestling match'
    ];
    return unusualEvents;
  }
}